version: 2.1

jobs:
  checkstyle:
    docker:
      - image: cimg/openjdk:21.0.8
    steps:
      - checkout
      - run:
          name: "Install Maven"
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: "Run Checkstyle"
          command: "mvn checkstyle:check"

workflows:
  checkstyle-workflow:
    jobs:
      - checkstyle